### DISCUSSION TITLE
first opening : no toolbar and no tree structure from default template

### DISCUSSION THREAD

**Discussion by pierrevedel** [eclipse-syson/syson#1379] [Q&A] [answered]
Hello
My organisation IT hss just installed the local app. At the first opening, I am trying ot launch the batmobile template and it seems to miss the 'toolbar' in genral view and the 'tree structure' of batmobile in explorer
what could have been wrong in installation ?

![image](https://github.com/user-attachments/assets/0da1c8b8-ba3e-4eb1-bb08-c0d2b2b19e44)

thank you
pierre

**Comment by AxelRICHARD** [comment]
Hello Pierre,

Thank you for your interest in SysON.
It's strange, I've never seen that before.
It seems the Explorer view and the General View are loading.

My questions below:

1. What happens if you try to refresh the page?
2. Do you experience the same problem with the "SysMLv2" template?
3. Which version of SysON are you using?

Regards,

**Reply by pierrevedel** [reply]
hello richard, thank for your answer
when refreshing page, I still have the infinite loading situation
I experience the same situation for every default template
IT has reinstalled the soft and we are now with v2025.4.9experiencing the same problem
I cannot give more information about installation but I can forward them some questions (or live chat)
thank you

**Reply by AxelRICHARD** [reply]
Is your SysON server on the same machine than the client one?
Can you check your "Network" tab in your Web Browser's dev tools? And check the subscriptions and graphql requests don't return any error?
<img width="820" alt="Capture d’écran 2025-06-16 à 16 15 19" src="https://github.com/user-attachments/assets/03e45f5d-7f9a-4293-a829-048ebfa1572a" />
Could you also check the SysON server console? and the Web Browser's console in your dev tools?

May be there is a network problem between  the client and the server?

**Reply by afernique** [reply]
Dear AxelRICHARD

syson is served behind our company https reverse proxy (nginx) which redirect https to local server port 8080 on https

```
    location / {
        include proxy_params;
        proxy_pass https://10.129.24.48:8080;
    }
```

on local server syson is run with docker-compose just adding self-signed certificate

```
  app:
    restart: unless-stopped
    image: "${IMAGE_TAG:-eclipsesyson/syson:v2025.4.9}"
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database/postgres
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
      SIRIUS_COMPONENTS_CORS_ALLOWEDORIGINPATTERNS: "*"
      SERVER_PORT: 8080
    volumes:
      - /root/syson/certs:/home/syson/certs
    entrypoint:
      - java
      - -jar
      - /syson-application.jar
      - --server.ssl.key-store=/home/syson/certs/lcpi.jks
      - --server.ssl.key-store-password=lcpi
      - --server.ssl.key-store-type=JKS
      - --server.ssl.key-alias=lcpi-syson.intram.ensam.eu
      - --server.ssl.key-password=lcpi
    depends_on:

```

accessing server directly make the batmobile project appear
![image](https://github.com/user-attachments/assets/e01c1e06-c0a1-4c0e-a8ac-bef2fa40a80a)

whili we're testing i suppose we could just use internal ip/port https://10.129.24.48:8080/projects
