### DISCUSSION TITLE
Crypto: randomUUID() is only available in a secure context

### DISCUSSION THREAD

**Discussion by pwretmo** [eclipse-syson/syson#563] [Q&A] [answered]
The frontend app makes use of the [Crypto: randomUUID()] method from the [Web Crypto API]. That method is only available in [secure contexts]. Hence the application only works when using HTTPS or when running on localhost (which is also a secure context). In non-secure contexts, the web app fails with `Uncaught TypeError: crypto.randomUUID is not a function` and the browser does not render any content.

The tool looks very promising! Great work!

[Crypto: randomUUID()]: https://developer.mozilla.org/en-US/docs/Web/API/Crypto/randomUUID
[Web Crypto API]: https://developer.mozilla.org/en-US/docs/Web/API/Web_Crypto_API
[secure contexts]: https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts

**Comment by AxelRICHARD** [comment, marked as answer]
Thank you!
Yes you're right, the application only works when using HTTPS or when running on localhost (which is also a secure context).
In the recently recently released documentation, a section is dedicated to this subject.
Please see: https://doc.mbse-syson.org/syson/main/installation-guide/how-tos/https.html 
(Note that our solution is for tests purpose only. For production deployments, you will need to obtain a valid certificate from a trusted CA to ensure secure and reliable communication.).

**Comment by aranvir** [comment]
Hi, I ran into the same issue when trying to run it from docker on a server in my local network.

Would be great to extend the docker compose instructions with how to add the keystore to the template.

For example, I used this now:
```yaml
version: "3.8"
services:
  database:
    image: postgres:12
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    networks:
      - syson
  app:
    image: eclipsesyson/syson:v2024.7.0
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database/postgres
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
      SIRIUS_COMPONENTS_CORS_ALLOWEDORIGINPATTERNS: "*"
      SERVER_PORT: 8080
    volumes:
      - ./keystore.jks:/keystore.jks
    depends_on:
      - database
    networks:
      - syson
    entrypoint:
      - java
      - -jar
      - /app.jar
      - --server.ssl.key-store=./keystore.jks
      - --server.ssl.key-store-password=password
      - --server.ssl.key-store-type=JKS
      - --server.ssl.key-alias=myalias
      - --server.ssl.key-password=password
networks:
  syson:
```
